nfl_players_part1 = [
    {'name': 'Abanikanda, Israel', 'position': 'RB', 'team': 'DAL', 'college': 'Pittsburgh'},
    {'name': 'Abdullah, Ameer', 'position': 'RB', 'team': 'JAX', 'college': 'Nebraska'},
    {'name': 'Abrams-Draine, Kris', 'position': 'CB', 'team': 'DEN', 'college': 'Missouri'},
    {'name': 'Adebayo, Tosin', 'position': 'DT', 'team': 'MIN', 'college': 'Northwestern'},
    {'name': 'Adkins, Nate', 'position': 'TE', 'team': 'DEN', 'college': 'Miami (OH)'},
    {'name': 'Agnew, Jamal', 'position': 'WR', 'team': 'JAX', 'college': 'South Carolina'},
    {'name': 'Ahmed, Salvon', 'position': 'RB', 'team': 'MIA', 'college': 'Washington'},
    {'name': 'Aiyuk, Brandon', 'position': 'WR', 'team': 'SF', 'college': 'Arizona State'},
    {'name': 'Ajayi, Sunday', 'position': 'LB', 'team': 'GB', 'college': 'Pittsburgh'},
    {'name': 'Akbar, A.J.', 'position': 'S', 'team': 'MIA', 'college': 'Louisville'},
    {'name': 'Allen, Brandon', 'position': 'QB', 'team': 'SF', 'college': 'Arkansas'},
    {'name': 'Allen, Davis', 'position': 'TE', 'team': 'LAR', 'college': 'Clemson'},
    {'name': 'Allen, Devon', 'position': 'LB', 'team': 'NYG', 'college': 'Tulane'},
    {'name': 'Allen, Josh', 'position': 'QB', 'team': 'BUF', 'college': 'Wyoming'},
    {'name': 'Allen, Keenan', 'position': 'WR', 'team': 'CHI', 'college': 'California'},
    {'name': 'Allen, Kyle', 'position': 'QB', 'team': 'PIT', 'college': 'Houston'},
    {'name': 'Allen, Marcus', 'position': 'S', 'team': 'PIT', 'college': 'Penn State'},
    {'name': 'Alualu, Tyson', 'position': 'DT', 'team': 'DET', 'college': 'California'},
    {'name': 'Amani, Brian', 'position': 'CB', 'team': 'TEN', 'college': 'Louisville'},
    {'name': 'Amaral, Noah', 'position': 'RB', 'team': 'NYG', 'college': 'UCLA'},
    {'name': 'Amendola, Danny', 'position': 'WR', 'team': 'HOU', 'college': 'Texas Tech'},
    {'name': 'Anderson, C.J.', 'position': 'RB', 'team': 'WAS', 'college': 'California'},
    {'name': 'Anderson, Derek', 'position': 'QB', 'team': 'BUF', 'college': 'Oregon State'},
    {'name': 'Anderson, Henry', 'position': 'DT', 'team': 'LAC', 'college': 'Stanford'},
    {'name': 'Anderson, Mark', 'position': 'DE', 'team': 'SEA', 'college': 'Alabama'},
    {'name': 'Anderson, Stephen', 'position': 'TE', 'team': 'LAC', 'college': 'Georgia'},
    {'name': 'Andrews, Mark', 'position': 'TE', 'team': 'BAL', 'college': 'Oklahoma'},
    {'name': 'Ankou, Eli', 'position': 'DT', 'team': 'ATL', 'college': 'UCLA'},
    {'name': 'Anzalone, Alex', 'position': 'LB', 'team': 'DET', 'college': 'Florida'},
    {'name': 'Aona, John', 'position': 'LS', 'team': 'LV', 'college': 'LSU'},
    {'name': 'Apple, Eli', 'position': 'CB', 'team': 'MIA', 'college': 'Ohio State'},
    {'name': 'Arcega-Whiteside, J.J.', 'position': 'WR', 'team': 'SEA', 'college': 'Stanford'},
    {'name': 'Archibong, Moses', 'position': 'DE', 'team': 'NYG', 'college': 'Princeton'},
    {'name': 'Ardarius, Matt', 'position': 'S', 'team': 'BAL', 'college': 'TCU'},
    {'name': 'Armah, Alex', 'position': 'FB', 'team': 'CAR', 'college': 'West Georgia'},
    {'name': 'Armstead, Arik', 'position': 'DE', 'team': 'SF', 'college': 'Oregon'},
    {'name': 'Armstead, Ryquell', 'position': 'RB', 'team': 'JAX', 'college': 'Temple'},
    {'name': 'Armstrong, Cornell', 'position': 'DE', 'team': 'DAL', 'college': 'USC'},
    {'name': 'Arnold, Dan', 'position': 'TE', 'team': 'LAC', 'college': 'Iowa'},
    {'name': 'Arnold, Dorian', 'position': 'S', 'team': 'CIN', 'college': 'Clemson'},
    {'name': 'Arrington, Kyle', 'position': 'CB', 'team': 'KC', 'college': 'Wake Forest'},
    {'name': 'Asiasi, Devin', 'position': 'TE', 'team': 'CIN', 'college': 'UCLA'},
    {'name': 'Ateman, Marcell', 'position': 'WR', 'team': 'LV', 'college': 'Oklahoma State'},
    {'name': 'Atkins, John', 'position': 'DT', 'team': 'CIN', 'college': 'Georgia'},
    {'name': 'Atkins, Jonathan', 'position': 'S', 'team': 'BUF', 'college': 'UCF'},
    {'name': 'Atkinson, Marcus', 'position': 'DT', 'team': 'MIA', 'college': 'Florida State'},
    {'name': 'Au, Eric', 'position': 'S', 'team': 'PHI', 'college': 'Oregon'},
    {'name': 'Aumavae-Laulu, Malaesala', 'position': 'OT', 'team': 'BAL', 'college': 'Oregon'},
    {'name': 'Austin, Alex', 'position': 'WR', 'team': 'NO', 'college': 'Texas'},
    {'name': 'Austin, Kevin', 'position': 'WR', 'team': 'LAC', 'college': 'Clemson'},
    {'name': 'Avery, Andre', 'position': 'LB', 'team': 'CIN', 'college': 'Texas Tech'},
    {'name': 'Avery, Genard', 'position': 'LB', 'team': 'PHI', 'college': 'Memphis'},
    {'name': 'Avila, Erick', 'position': 'OT', 'team': 'KC', 'college': 'TCU'},
    {'name': 'Awosika, Kayode', 'position': 'OG', 'team': 'PHI', 'college': 'Buffalo'},
    {'name': 'Ayers, Shamel', 'position': 'DE', 'team': 'DEN', 'college': 'Missouri'},
    {'name': 'Baccellia, Andre', 'position': 'WR', 'team': 'ARI', 'college': 'Washington'},
    {'name': 'Bachie, Joe', 'position': 'LB', 'team': 'CLE', 'college': 'Cincinnati'},
    {'name': 'Backhaus, Matt', 'position': 'OG', 'team': 'KC', 'college': 'Pittsburgh'},
    {'name': 'Badgley, Mike', 'position': 'K', 'team': 'DET', 'college': 'Miami (FL)'},
    {'name': 'Bagne, Matt', 'position': 'TE', 'team': 'ATL', 'college': 'Wake Forest'},
    {'name': 'Bailey, Jake', 'position': 'K', 'team': 'NYJ', 'college': 'Texas A&M'},
    {'name': 'Bailey, Marcus', 'position': 'CB', 'team': 'DAL', 'college': 'Purdue'},
    {'name': 'Bailey, Travis', 'position': 'DT', 'team': 'LV', 'college': 'UCF'},
    {'name': 'Baine, Seth', 'position': 'P', 'team': 'DEN', 'college': 'Colorado'},
    {'name': 'Bair, Skye', 'position': 'TE', 'team': 'SF', 'college': 'Utah State'},
    {'name': 'Baker, Budda', 'position': 'S', 'team': 'ARI', 'college': 'Washington'},
    {'name': 'Baker, Jerome', 'position': 'LB', 'team': 'MIA', 'college': 'Ohio State'},
    {'name': 'Baker, Kelvin', 'position': 'CB', 'team': 'HOU', 'college': 'TCU'},
    {'name': 'Baker, Mekhi', 'position': 'OT', 'team': 'NYG', 'college': 'Northwestern'},
    {'name': 'Baldonado, Habakkuk', 'position': 'DE', 'team': 'JAX', 'college': 'Pittsburgh'},
    {'name': 'Baldwin, Michael', 'position': 'TE', 'team': 'KC', 'college': 'Stanford'},
    {'name': 'Baldy, Shane', 'position': 'LB', 'team': 'WAS', 'college': 'Penn State'},
    {'name': 'Balfour, Tyler', 'position': 'S', 'team': 'CLE', 'college': 'Ohio State'},
    {'name': 'Ball, Alex', 'position': 'LS', 'team': 'HOU', 'college': 'Alabama'},
    {'name': 'Ball, T.J.', 'position': 'CB', 'team': 'NO', 'college': 'Iowa'},
    {'name': 'Ballas, Jake', 'position': 'OG', 'team': 'MIA', 'college': 'Nebraska'},
    {'name': 'Ballengee, Matt', 'position': 'OT', 'team': 'SEA', 'college': 'Oklahoma'},
    {'name': 'Bancroft, Mike', 'position': 'CB', 'team': 'NE', 'college': 'Purdue'},
    {'name': 'Bandujo, Frank', 'position': 'OG', 'team': 'KC', 'college': 'Iowa'},
    {'name': 'Bandy, Michael', 'position': 'WR', 'team': 'CIN', 'college': 'Texas A&M'},
    {'name': 'Banjo, Chris', 'position': 'S', 'team': 'ARI', 'college': 'SMU'},
    {'name': 'Banks, Deonte', 'position': 'CB', 'team': 'NYG', 'college': 'North Carolina'},
    {'name': 'Baptiste, Josh', 'position': 'CB', 'team': 'WAS', 'college': 'Baylor'},
    {'name': 'Barber, Peyton', 'position': 'RB', 'team': 'PHI', 'college': 'Auburn'},
    {'name': 'Barco, John', 'position': 'P', 'team': 'BUF', 'college': 'Florida State'},
    {'name': 'Bard, Michael', 'position': 'TE', 'team': 'MIA', 'college': 'USC'},
    {'name': 'Barkley, Saquon', 'position': 'RB', 'team': 'PHI', 'college': 'Penn State'},
    {'name': 'Barlo, Nathan', 'position': 'OG', 'team': 'GB', 'college': 'LSU'},
    {'name': 'Barnes, Krys', 'position': 'LB', 'team': 'GB', 'college': 'Purdue'},
    {'name': 'Barnett, Derek', 'position': 'DE', 'team': 'NO', 'college': 'Tennessee'},
    {'name': 'Barr, Anthony', 'position': 'LB', 'team': 'DAL', 'college': 'UCLA'},
    {'name': 'Barrett, Derek', 'position': 'OT', 'team': 'HOU', 'college': 'Florida'},
    {'name': 'Barrett, Ian', 'position': 'LB', 'team': 'LV', 'college': 'Ohio State'},
    {'name': 'Barrett, Noah', 'position': 'WR', 'team': 'CLE', 'college': 'Michigan State'},
    {'name': 'Barrow, Alex', 'position': 'DT', 'team': 'CAR', 'college': 'Temple'},
    {'name': 'Barth, Connor', 'position': 'K', 'team': 'NYJ', 'college': 'Florida'},
    {'name': 'Barton, Cody', 'position': 'LB', 'team': 'DEN', 'college': 'Utah'},
    {'name': 'Barton, Joe', 'position': 'OT', 'team': 'MIN', 'college': 'Notre Dame'},
    {'name': 'Barty, James', 'position': 'DT', 'team': 'NO', 'college': 'Georgia'},
    {'name': 'Baskerville, Brian', 'position': 'DE', 'team': 'PIT', 'college': 'Texas'},
    {'name': 'Bates, Jessie', 'position': 'S', 'team': 'ATL', 'college': 'Wake Forest'},
    {'name': 'Bates, Josh', 'position': 'CB', 'team': 'DAL', 'college': 'Purdue'},
    {'name': 'Bates, Marcus', 'position': 'TE', 'team': 'KC', 'college': 'Stanford'},
    {'name': 'Battista, Brandon', 'position': 'P', 'team': 'CIN', 'college': 'Tennessee'},
    {'name': 'Baughman, C.J.', 'position': 'S', 'team': 'LAC', 'college': 'Washington State'},
    {'name': 'Baum, Zach', 'position': 'OG', 'team': 'NYG', 'college': 'Washington'},
    {'name': 'Bawden, Nick', 'position': 'FB', 'team': 'DET', 'college': 'San Diego State'},
    {'name': 'Baxter, Chris', 'position': 'DE', 'team': 'MIA', 'college': 'Penn State'},
    {'name': 'Baylis, Evan', 'position': 'TE', 'team': 'NO', 'college': 'Washington'},
    {'name': 'Beal, Trey', 'position': 'LB', 'team': 'LV', 'college': 'TCU'},
    {'name': 'Beamish, Connor', 'position': 'OT', 'team': 'BUF', 'college': 'Michigan'},
    {'name': 'Beard, Andrew', 'position': 'DT', 'team': 'TEN', 'college': 'Stanford'},
    {'name': 'Beathard, C.J.', 'position': 'QB', 'team': 'JAX', 'college': 'Iowa'},
    {'name': 'Beavers, Dare', 'position': 'LB', 'team': 'SEA', 'college': 'Virginia Tech'},
    {'name': 'Beck, Andrew', 'position': 'TE', 'team': 'DEN', 'college': 'Texas'},
    {'name': 'Beck, Jackson', 'position': 'LB', 'team': 'DEN', 'college': 'Purdue'},
    {'name': 'Beck, Trenton', 'position': 'DE', 'team': 'KC', 'college': 'Georgia'},
    {'name': 'Beckett, Nick', 'position': 'S', 'team': 'ATL', 'college': 'Texas Tech'},
    {'name': 'Beckley, Trey', 'position': 'RB', 'team': 'HOU', 'college': 'Texas A&M'},
    {'name': 'Bedell, Jordan', 'position': 'RB', 'team': 'CLE', 'college': 'Iowa'},
    {'name': 'Beecher, Mason', 'position': 'LS', 'team': 'NYJ', 'college': 'Oklahoma'},
    {'name': 'Beefelt, Zach', 'position': 'OT', 'team': 'NYG', 'college': 'Notre Dame'},
    {'name': 'Behm, Adam', 'position': 'OG', 'team': 'CHI', 'college': 'Wisconsin'},
    {'name': 'Bekkedam, C.J.', 'position': 'DE', 'team': 'KC', 'college': 'Washington'},
    {'name': 'Beldon, Austin', 'position': 'WR', 'team': 'NYJ', 'college': 'USC'},
    {'name': 'Belfort, Chris', 'position': 'LB', 'team': 'CIN', 'college': 'Texas'},
    {'name': 'Bell, Blake', 'position': 'TE', 'team': 'CLE', 'college': 'Oklahoma'},
    {'name': 'Bell, Brandon', 'position': 'S', 'team': 'NYG', 'college': 'Clemson'},
    {'name': 'Bell, Jack', 'position': 'CB', 'team': 'SEA', 'college': 'Washington'},
    {'name': 'Bell, James', 'position': 'OT', 'team': 'CHI', 'college': 'Ohio State'},
    {'name': 'Bell, K.J.', 'position': 'CB', 'team': 'SF', 'college': 'Colorado State'},
    {'name': 'Bell, Mark', 'position': 'DT', 'team': 'BAL', 'college': 'Michigan'},
    {'name': 'Bell, Mike', 'position': 'LB', 'team': 'IND', 'college': 'Cincinnati'},
    {'name': 'Bell, Nick', 'position': 'S', 'team': 'PHI', 'college': 'Arizona'},
    {'name': 'Bellamy, Blake', 'position': 'WR', 'team': 'KC', 'college': 'Illinois'},
    {'name': 'Bellow, J.T.', 'position': 'RB', 'team': 'TEN', 'college': 'Oklahoma'},
    {'name': 'Bellows, J.R.', 'position': 'OT', 'team': 'SF', 'college': 'Oregon'},
    {'name': 'Beltran, Mike', 'position': 'OG', 'team': 'DAL', 'college': 'TCU'},
    {'name': 'Benavides, Daniel', 'position': 'DE', 'team': 'WAS', 'college': 'Louisville'},
    {'name': 'Benck, John', 'position': 'TE', 'team': 'DET', 'college': 'Penn State'},
    {'name': 'Bender, Josh', 'position': 'K', 'team': 'NYG', 'college': 'UCLA'},
    {'name': 'Benefield, Ryan', 'position': 'P', 'team': 'KC', 'college': 'Texas'},
    {'name': 'Benjamin, Kelvin', 'position': 'WR', 'team': 'LAC', 'college': 'Florida State'},
    {'name': 'Benjamin, Travis', 'position': 'WR', 'team': 'WAS', 'college': 'Miami (FL)'},
    {'name': 'Bennett, Carter', 'position': 'TE', 'team': 'DAL', 'college': 'Ohio State'},
    {'name': 'Bennett, Michael', 'position': 'DE', 'team': 'SF', 'college': 'Washington'},
    {'name': 'Bentley, Jake', 'position': 'LB', 'team': 'CLE', 'college': 'Notre Dame'},
    {'name': 'Benton, Keeanu', 'position': 'DT', 'team': 'PIT', 'college': 'Wisconsin'},
    {'name': 'Benwick, Dylan', 'position': 'OT', 'team': 'MIN', 'college': 'Iowa'},
    {'name': 'Berg, Brandon', 'position': 'OG', 'team': 'ATL', 'college': 'Oklahoma'},
    {'name': 'Berger, Eric', 'position': 'CB', 'team': 'BUF', 'college': 'North Carolina'},
    {'name': 'Berghoff, Brad', 'position': 'DT', 'team': 'MIA', 'college': 'Purdue'},
    {'name': 'Berglund, Cody', 'position': 'DE', 'team': 'LV', 'college': 'Stanford'},
    {'name': 'Berk, Trey', 'position': 'LB', 'team': 'TEN', 'college': 'Alabama'},
    {'name': 'Berman, David', 'position': 'OG', 'team': 'CHI', 'college': 'Penn State'},
    {'name': 'Bernard, Terrel', 'position': 'RB', 'team': 'CIN', 'college': 'UCF'},
    {'name': 'Bernstein, Matt', 'position': 'TE', 'team': 'NYJ', 'college': 'Texas Tech'},
    {'name': 'Berrios, Braxton', 'position': 'WR', 'team': 'MIA', 'college': 'Miami (FL)'},
    {'name': 'Berry, Brett', 'position': 'CB', 'team': 'LAR', 'college': 'Ohio State'},
    {'name': 'Berry, Vernon', 'position': 'S', 'team': 'SF', 'college': 'Notre Dame'},
    {'name': 'Bertrand, Jake', 'position': 'LB', 'team': 'DET', 'college': 'Washington'},
    {'name': 'Beschorner, Michael', 'position': 'OG', 'team': 'GB', 'college': 'Wisconsin'},
    {'name': 'Bessent, Robert', 'position': 'DE', 'team': 'SEA', 'college': 'Florida'},
    {'name': 'Bethel, Justin', 'position': 'CB', 'team': 'MIA', 'college': 'Baylor'},
    {'name': 'Bethel-Thompson, McLeod', 'position': 'QB', 'team': 'NO', 'college': 'Tulane'},
    {'name': 'Bethea, Justin', 'position': 'S', 'team': 'NYG', 'college': 'UCLA'},
    {'name': 'Beverly, Joe', 'position': 'LB', 'team': 'TEN', 'college': 'Texas'},
    {'name': 'Beyer, Jacob', 'position': 'OT', 'team': 'BAL', 'college': 'Clemson'},
    {'name': 'Bibbs, Kapri', 'position': 'RB', 'team': 'WAS', 'college': 'Colorado State'},
    {'name': 'Bick, Trevor', 'position': 'DT', 'team': 'CIN', 'college': 'Ohio State'},
    {'name': 'Bickford, Adam', 'position': 'TE', 'team': 'JAX', 'college': 'UCF'},
    {'name': 'Biegel, Vince', 'position': 'LB', 'team': 'PHI', 'college': 'Wisconsin'},
    {'name': 'Bierria, Peter', 'position': 'LB', 'team': 'LAC', 'college': 'Washington'},
    {'name': 'Bigelow, David', 'position': 'DE', 'team': 'CAR', 'college': 'Stanford'},
    {'name': 'Bignall, Eric', 'position': 'CB', 'team': 'NYG', 'college': 'Arizona State'},
    {'name': 'Bilbo, Jalen', 'position': 'S', 'team': 'CHI', 'college': 'LSU'},
    {'name': 'Biles, Jordan', 'position': 'OT', 'team': 'HOU', 'college': 'Texas Tech'},
    {'name': 'Bilger, Cody', 'position': 'OG', 'team': 'DEN', 'college': 'Oklahoma'},
    {'name': 'Billings, Andrew', 'position': 'DT', 'team': 'DAL', 'college': 'Baylor'},
    {'name': 'Bing, D.J.', 'position': 'CB', 'team': 'ARI', 'college': 'UCLA'},
    {'name': 'Binns, Armon', 'position': 'DE', 'team': 'CLE', 'college': 'Cincinnati'},
    {'name': 'Bird, Daniel', 'position': 'TE', 'team': 'NYJ', 'college': 'UCF'},
    {'name': 'Birdsong, Nick', 'position': 'QB', 'team': 'LV', 'college': 'Oregon State'},
    {'name': 'Bishop, Brian', 'position': 'LB', 'team': 'BUF', 'college': 'Clemson'},
    {'name': 'Bishop, Kalel', 'position': 'WR', 'team': 'PHI', 'college': 'UCLA'},
    {'name': 'Bishop, Tyler', 'position': 'OG', 'team': 'DET', 'college': 'Wisconsin'},
    {'name': 'Bitting, John', 'position': 'P', 'team': 'LAC', 'college': 'Texas'},
    {'name': 'Biven, Cody', 'position': 'LS', 'team': 'MIN', 'college': 'Notre Dame'},
    {'name': 'Bivens, Branden', 'position': 'DT', 'team': 'JAX', 'college': 'Florida State'},
    {'name': 'Bizjak, Sean', 'position': 'DE', 'team': 'NO', 'college': 'Michigan'},
    {'name': 'Black, Chris', 'position': 'CB', 'team': 'PIT', 'college': 'Ohio State'},
    {'name': 'Black, Dylan', 'position': 'S', 'team': 'DAL', 'college': 'Oklahoma'},
    {'name': 'Black, J.R.', 'position': 'TE', 'team': 'SF', 'college': 'Penn State'},
    {'name': 'Black, Tyler', 'position': 'OT', 'team': 'IND', 'college': 'NC State'},
    {'name': 'Blackmon, Julian', 'position': 'CB', 'team': 'IND', 'college': 'Utah'},
    {'name': 'Blackmon, Justin', 'position': 'WR', 'team': 'JAX', 'college': 'Clemson'},
    {'name': 'Blacknell, Colin', 'position': 'WR', 'team': 'LV', 'college': 'California'},
    {'name': 'Blackson, Angelo', 'position': 'DT', 'team': 'BAL', 'college': 'Auburn'},
    {'name': 'Blackwell, Carl', 'position': 'LB', 'team': 'NYG', 'college': 'Texas Tech'},
    {'name': 'Bladen, Bryce', 'position': 'DE', 'team': 'MIA', 'college': 'Iowa'},
    {'name': 'Blagg, Tyler', 'position': 'OG', 'team': 'CHI', 'college': 'Kansas State'},
    {'name': 'Blair, Marquise', 'position': 'S', 'team': 'SEA', 'college': 'Utah'},
    {'name': 'Blake, Christian', 'position': 'WR', 'team': 'BAL', 'college': 'Louisville'},
    {'name': 'Blalock, Jake', 'position': 'TE', 'team': 'WAS', 'college': 'Oregon'},
    {'name': 'Blanch, Paul', 'position': 'P', 'team': 'CIN', 'college': 'Nebraska'},
    {'name': 'Bland, DaRon', 'position': 'CB', 'team': 'DAL', 'college': 'Fresno State'},
    {'name': 'Blankenship, Rodrigo', 'position': 'K', 'team': 'IND', 'college': 'Georgia'},
    {'name': 'Blanton, Kendall', 'position': 'DT', 'team': 'HOU', 'college': 'Texas A&M'},
    {'name': 'Blasigh, Connor', 'position': 'LB', 'team': 'TEN', 'college': 'UCF'},
    {'name': 'Blazevich, Jordan', 'position': 'TE', 'team': 'LAC', 'college': 'Georgia'},
    {'name': 'Bleck, J.R.', 'position': 'OG', 'team': 'DET', 'college': 'Michigan State'},
    {'name': 'Blessing, Jake', 'position': 'DE', 'team': 'CLE', 'college': 'Ohio State'},
    {'name': 'Blichfeldt, Bryce', 'position': 'WR', 'team': 'SF', 'college': 'Oregon State'},
    {'name': 'Blount, LeGarrette', 'position': 'RB', 'team': 'PHI', 'college': 'Oregon'},
    {'name': 'Blount, Myles', 'position': 'S', 'team': 'LV', 'college': 'Texas Tech'},
    {'name': 'Blue, Deon', 'position': 'CB', 'team': 'BUF', 'college': 'Arizona State'},
    {'name': 'Blue, Jalen', 'position': 'WR', 'team': 'CHI', 'college': 'Colorado'},
    {'name': 'Blum, Nick', 'position': 'OT', 'team': 'NYG', 'college': 'Penn State'},
    {'name': 'Blythe, Austin', 'position': 'C', 'team': 'SEA', 'college': 'Iowa'},
    {'name': 'Board, C.J.', 'position': 'LB', 'team': 'BAL', 'college': 'Pittsburgh'},
    {'name': 'Bober, Kyle', 'position': 'OT', 'team': 'ATL', 'college': 'Notre Dame'},
    {'name': 'Bobo, Jake', 'position': 'WR', 'team': 'SEA', 'college': 'UCLA'},
    {'name': 'Bocage, Joe', 'position': 'S', 'team': 'NO', 'college': 'LSU'},
    {'name': 'Bockman, Kurt', 'position': 'DT', 'team': 'JAX', 'college': 'Stanford'},
    {'name': 'Boddie, Kendrick', 'position': 'RB', 'team': 'DAL', 'college': 'Oklahoma State'},
    {'name': 'Boden, Evan', 'position': 'OG', 'team': 'MIN', 'college': 'Wisconsin'},
    {'name': 'Bodine, Russell', 'position': 'C', 'team': 'CIN', 'college': 'North Carolina'},
    {'name': 'Boehringer, Moritz', 'position': 'WR', 'team': 'MIN', 'college': 'None'},
    {'name': 'Boehm, Evan', 'position': 'C', 'team': 'ARI', 'college': 'Missouri'},
    {'name': 'Boggs, Peter', 'position': 'DE', 'team': 'NYJ', 'college': 'North Carolina'},
    {'name': 'Bolden, Brandon', 'position': 'WR', 'team': 'MIA', 'college': 'Ole Miss'},
    {'name': 'Bolden, Victor', 'position': 'RB', 'team': 'DEN', 'college': 'Oregon State'},
    {'name': 'Boles, Cooper', 'position': 'OT', 'team': 'LV', 'college': 'Texas'},
    {'name': 'Boling, Clint', 'position': 'OG', 'team': 'CIN', 'college': 'Georgia'},
    {'name': 'Bolles, Garett', 'position': 'OT', 'team': 'DEN', 'college': 'Utah'},
    {'name': 'Bomar, Chris', 'position': 'QB', 'team': 'CIN', 'college': 'Texas Tech'},
    {'name': 'Bond, Du'Vonta', 'position': 'FB', 'team': 'HOU', 'college': 'LSU'},
    {'name': 'Bond, Joe', 'position': 'OG', 'team': 'CHI', 'college': 'Oklahoma'},
    {'name': 'Bonner, Chris', 'position': 'CB', 'team': 'PHI', 'college': 'Nebraska'},
    {'name': 'Bono, Tim', 'position': 'P', 'team': 'CLE', 'college': 'Washington'},
    {'name': 'Book, Ian', 'position': 'QB', 'team': 'NO', 'college': 'Notre Dame'},
    {'name': 'Booker, Devontae', 'position': 'RB', 'team': 'CHI', 'college': 'Utah'},
    {'name': 'Booker, Lorenzo', 'position': 'DT', 'team': 'LAR', 'college': 'Nebraska'},
    {'name': 'Boone, Andrew', 'position': 'DE', 'team': 'NYJ', 'college': 'Michigan'},
    {'name': 'Boone, Brock', 'position': 'WR', 'team': 'MIA', 'college': 'USC'},
    {'name': 'Boone, Mike', 'position': 'OG', 'team': 'SF', 'college': 'Stanford'},
    {'name': 'Booth, Andrew', 'position': 'CB', 'team': 'MIN', 'college': 'Clemson'},
    {'name': 'Booth, J.D.', 'position': 'S', 'team': 'LV', 'college': 'Texas Tech'},
    {'name': 'Borders, Breon', 'position': 'CB', 'team': 'BAL', 'college': 'Arizona State'},
    {'name': 'Borden, Brett', 'position': 'OT', 'team': 'GB', 'college': 'Wisconsin'},
    {'name': 'Borelli, Nick', 'position': 'LB', 'team': 'WAS', 'college': 'Northwestern'},
    {'name': 'Borg, Matt', 'position': 'TE', 'team': 'CIN', 'college': 'Purdue'},
    {'name': 'Borges, Dylan', 'position': 'OG', 'team': 'DET', 'college': 'Ohio State'},
    {'name': 'Boring, Alex', 'position': 'DT', 'team': 'TEN', 'college': 'North Carolina'},
    {'name': 'Borland, Chris', 'position': 'LB', 'team': 'SF', 'college': 'Wisconsin'},
    {'name': 'Bornemann, Nathan', 'position': 'DE', 'team': 'DAL', 'college': 'Iowa'},
    {'name': 'Borregales, Jose', 'position': 'K', 'team': 'MIA', 'college': 'FIU'},
    {'name': 'Bosher, Matt', 'position': 'P', 'team': 'ATL', 'college': 'Miami (FL)'},
    {'name': 'Bosley, Logan', 'position': 'OT', 'team': 'IND', 'college': 'Wisconsin'},
    {'name': 'Bossett, Austin', 'position': 'TE', 'team': 'NO', 'college': 'Stanford'},
    {'name': 'Bostic, Jon', 'position': 'LB', 'team': 'WAS', 'college': 'Florida'},
    {'name': 'Boswell, Chris', 'position': 'K', 'team': 'PIT', 'college': 'Rice'},
    {'name': 'Botkin, Tyler', 'position': 'OG', 'team': 'ARI', 'college': 'Oklahoma State'},
    {'name': 'Bottoms, Cody', 'position': 'CB', 'team': 'JAX', 'college': 'Clemson'},
    {'name': 'Bouchard, Evan', 'position': 'P', 'team': 'DAL', 'college': 'TCU'},
    {'name': 'Bough, Danny', 'position': 'DE', 'team': 'LAC', 'college': 'Texas A&M'},
    {'name': 'Boulware, J.J.', 'position': 'C', 'team': 'CHI', 'college': 'Florida State'},
    {'name': 'Bourne, Kendrick', 'position': 'WR', 'team': 'NE', 'college': 'Eastern Washington'},
    {'name': 'Bourne, Matt', 'position': 'WR', 'team': 'IND', 'college': 'Oregon'},
    {'name': 'Bove, Nick', 'position': 'LB', 'team': 'NYG', 'college': 'Miami (FL)'},
    {'name': 'Bowden, Lynn', 'position': 'RB', 'team': 'LV', 'college': 'Georgia'},
    {'name': 'Bowen, John', 'position': 'DE', 'team': 'BUF', 'college': 'Texas Tech'},
    {'name': 'Bowen, Mike', 'position': 'OG', 'team': 'CAR', 'college': 'Penn State'},
    {'name': 'Bower, Drew', 'position': 'DT', 'team': 'NYJ', 'college': 'Michigan'},
    {'name': 'Bowers, Brock', 'position': 'TE', 'team': 'LV', 'college': 'Georgia'},
    {'name': 'Bowers, Trent', 'position': 'CB', 'team': 'ARI', 'college': 'LSU'},
    {'name': 'Bowl, Jonathan', 'position': 'DE', 'team': 'CIN', 'college': 'Ohio State'},
    {'name': 'Bowles, Jeremy', 'position': 'S', 'team': 'DAL', 'college': 'North Carolina'},
    {'name': 'Bowman, Gabe', 'position': 'LB', 'team': 'SEA', 'college': 'Washington'},
    {'name': 'Bowser, Tyus', 'position': 'LB', 'team': 'BAL', 'college': 'Houston'},
    {'name': 'Box, Evan', 'position': 'OG', 'team': 'DEN', 'college': 'Oklahoma'},
    {'name': 'Boyce, Josh', 'position': 'WR', 'team': 'NE', 'college': 'TCU'},
    {'name': 'Boyd, Chris', 'position': 'CB', 'team': 'CIN', 'college': 'Michigan'},
    {'name': 'Boyd, Tyler', 'position': 'WR', 'team': 'CIN', 'college': 'Pittsburgh'},
    {'name': 'Boyer, Tyler', 'position': 'LB', 'team': 'DET', 'college': 'Michigan State'},
    {'name': 'Boykin, Miles', 'position': 'WR', 'team': 'PIT', 'college': 'Notre Dame'},
    {'name': 'Boyle, Nick', 'position': 'TE', 'team': 'BAL', 'college': 'Delaware'},
    {'name': 'Boyle, Tim', 'position': 'QB', 'team': 'NYG', 'college': 'Stanford'},
    {'name': 'Brabham, Cam', 'position': 'DT', 'team': 'MIA', 'college': 'Auburn'},
    {'name': 'Bradberry, James', 'position': 'CB', 'team': 'PHI', 'college': 'Samford'},
    {'name': 'Bradford, Shane', 'position': 'DE', 'team': 'SEA', 'college': 'Texas A&M'},
    {'name': 'Bradley, Dylan', 'position': 'OT', 'team': 'CLE', 'college': 'USC'},
    {'name': 'Bradley, Keese', 'position': 'LB', 'team': 'SF', 'college': 'UCLA'},
    {'name': 'Bradshaw, Ahmad', 'position': 'RB', 'team': 'NYG', 'college': 'Texas Tech'},
    {'name': 'Bradshaw, Kameron', 'position': 'CB', 'team': 'LV', 'college': 'Notre Dame'},
    {'name': 'Brady, Tom', 'position': 'QB', 'team': 'TB', 'college': 'Michigan'},
]
#part 2