nfl_teams = [{'city':'Arizona','teamName':'Cardinals','abv':'ari'},
             {'city':'Atlanta','teamName':'Falcons','abv':'atl'},
             {'city':'Baltimore','teamName':'Ravens','abv':'bal'},
             {'city':'Buffalo','teamName':'Bills','abv':'buf'},
             {'city':'Carolina','teamName':'Panthers','abv':'car'},
             {'city':'Chicago','teamName':'Bears','abv':'chi'},
             {'city':'Cincinnati','teamName':'Bengals','abv':'cin'},
             {'city':'Cleveland','teamName':'Browns','abv':'cle'},
             {'city':'Dallas','teamName':'Cowboys','abv':'dal'},
             {'city':'Denver','teamName':'Broncos','abv':'den'},
             {'city':'Detroit','teamName':'Lions','abv':'det'},
             {'city':'Green Bay','teamName':'Packers','abv':'gb'},
             {'city':'Houston','teamName':'Texans','abv':'hou'},
             {'city':'Indianapolis','teamName':'Colts','abv':'ind'},
             {'city':'Jacksonville', 'teamName': 'Jaguars', 'abv': 'jax'},
             {'city': 'Kansas City', 'teamName': 'Chiefs', 'abv': 'kc'},
             {'city': 'Las Vegas', 'teamName': 'Raiders', 'abv': 'lv'},
             {'city': 'Los Angeles', 'teamName': 'Rams', 'abv': 'lar'},
             {'city': 'Los Angeles', 'teamName': 'Chargers', 'abv': 'lac'},
             {'city': 'Miami', 'teamName': 'Dolphins', 'abv': 'mia'},
             {'city': 'Minnesota', 'teamName': 'Vikings', 'abv': 'min'},
             {'city': "New England", "teamName": "Patriots", "abv": "ne"},
             {'city': "New Orleans", "teamName": "Saints", "abv": "no"},
             {'city': "New York", "teamName": "Giants", "abv": "nyg"},
             {'city': "New York", "teamName": "Jets", "abv": "nyj"},
             {'city': "Philadelphia", "teamName": "Eagles", "abv": "phi"},
             {'city': "Pittsburgh", "teamName": "Steelers", "abv": "pit"},
             {'city': "San Francisco", "teamName": "49ers", "abv": "sf"},
             {'city': "Seattle", "teamName": "Seahawks", "abv": "sea"},
             {'city': "Tampa Bay", "teamName": "Buccaneers", "abv": "tb"},
             {'city': "Tennessee", "teamName": "Titans", "abv": "ten"},
             {'city': "Washington", "teamName": "Football Team", "abv": "wsh"}]