# Sports/nfl/nfl_coaches.py
nfl_coaches = [
    {'team_abbr': 'ARI', 'team_name': 'Arizona Cardinals', 'coach': 'Jonathan Gannon'},
    {'team_abbr': 'ATL', 'team_name': 'Atlanta Falcons', 'coach': 'Raheem Morris'},
    {'team_abbr': 'BAL', 'team_name': 'Baltimore Ravens', 'coach': 'John Harbaugh'},
    {'team_abbr': 'BUF', 'team_name': 'Buffalo Bills', 'coach': 'Sean McDermott'},
    {'team_abbr': 'CAR', 'team_name': 'Carolina Panthers', 'coach': 'Dave Canales'},
    {'team_abbr': 'CHI', 'team_name': 'Chicago Bears', 'coach': 'Matt Eberflus'},
    {'team_abbr': 'CIN', 'team_name': 'Cincinnati Bengals', 'coach': 'Zac Taylor'},
    {'team_abbr': 'CLE', 'team_name': 'Cleveland Browns', 'coach': 'Kevin Stefanski'},
    {'team_abbr': 'DAL', 'team_name': 'Dallas Cowboys', 'coach': 'Mike McCarthy'},
    {'team_abbr': 'DEN', 'team_name': 'Denver Broncos', 'coach': 'Sean Payton'},
    {'team_abbr': 'DET', 'team_name': 'Detroit Lions', 'coach': 'Dan Campbell'},
    {'team_abbr': 'GB',  'team_name': 'Green Bay Packers', 'coach': 'Matt LaFleur'},
    {'team_abbr': 'HOU', 'team_name': 'Houston Texans', 'coach': 'DeMeco Ryans'},
    {'team_abbr': 'IND', 'team_name': 'Indianapolis Colts', 'coach': 'Shane Steichen'},
    {'team_abbr': 'JAX', 'team_name': 'Jacksonville Jaguars', 'coach': 'Doug Pederson'},
    {'team_abbr': 'KC',  'team_name': 'Kansas City Chiefs', 'coach': 'Andy Reid'},
    {'team_abbr': 'LV',  'team_name': 'Las Vegas Raiders', 'coach': 'Antonio Pierce'},
    {'team_abbr': 'LAC', 'team_name': 'Los Angeles Chargers', 'coach': 'Jim Harbaugh'},
    {'team_abbr': 'LAR', 'team_name': 'Los Angeles Rams', 'coach': 'Sean McVay'},
    {'team_abbr': 'MIA', 'team_name': 'Miami Dolphins', 'coach': 'Mike McDaniel'},
    {'team_abbr': 'MIN', 'team_name': 'Minnesota Vikings', 'coach': 'Kevin O\'Connell'},
    {'team_abbr': 'NE',  'team_name': 'New England Patriots', 'coach': 'Jerod Mayo'},
    {'team_abbr': 'NO',  'team_name': 'New Orleans Saints', 'coach': 'Dennis Allen'},
    {'team_abbr': 'NYG', 'team_name': 'New York Giants', 'coach': 'Brian Daboll'},
    {'team_abbr': 'NYJ', 'team_name': 'New York Jets', 'coach': 'Robert Saleh'},
    {'team_abbr': 'PHI', 'team_name': 'Philadelphia Eagles', 'coach': 'Nick Sirianni'},
    {'team_abbr': 'PIT', 'team_name': 'Pittsburgh Steelers', 'coach': 'Mike Tomlin'},
    {'team_abbr': 'SF',  'team_name': 'San Francisco 49ers', 'coach': 'Kyle Shanahan'},
    {'team_abbr': 'SEA', 'team_name': 'Seattle Seahawks', 'coach': 'Mike Macdonald'},
    {'team_abbr': 'TB',  'team_name': 'Tampa Bay Buccaneers', 'coach': 'Todd Bowles'},
    {'team_abbr': 'TEN', 'team_name': 'Tennessee Titans', 'coach': 'Brian Callahan'},
    {'team_abbr': 'WAS', 'team_name': 'Washington Commanders', 'coach': 'Dan Quinn'},
]