nhl_teams = [{'city':'Anaheim','teamName':'Ducks','abv':'ana'},
             {'city':'Arizona','teamName':'Coyotes','abv':'ari'},
             {'city':'Boston','teamName':'Bruins','abv':'bos'},
             {'city':'Buffalo','teamName':'Sabres','abv':'buf'},
             {'city':'Calgary','teamName':'Flames','abv':'cgy'},
             {'city':'Carolina','teamName':'Hurricanes','abv':'car'},
             {'city':'Chicago','teamName':'Blackhawks','abv':'chi'},
             {'city':'Colorado','teamName':'Avalanche','abv':'col'},
             {'city':'Columbus','teamName':'Blue Jackets','abv':'cbj'},
             {'city':'Dallas','teamName':'Stars','abv':'dal'},
             {'city':'Detroit','teamName':'Red Wings','abv':'det'},
             {'city':'Edmonton','teamName':'Oilers','abv':'edm'},
             {'city':'Florida','teamName':'Panthers','abv':'fla'},
             {'city':'Los Angeles', 'teamName': 'Kings', 'abv': 'la'},
             {'city':'Minnesota','teamName':'Wild','abv':'min'},
             {'city': 'Montreal', 'teamName': 'Canadiens', 'abv': 'mtl'},
             {'city': 'Nashville', 'teamName': 'Predators', 'abv': 'nsh'},
             {'city': 'New Jersey', 'teamName': 'Devils', 'abv': 'nj'},
             {'city': 'New York', 'teamName': 'Islanders', 'abv': 'nyi'},
             {'city': "New York", "teamName": "Rangers", "abv": "nyr"},
             {'city': "Ottawa", "teamName": "Senators", "abv": "ott"},
             {'city': "Philadelphia", "teamName": "Flyers", "abv": "phi"},
             {'city': "Pittsburgh", "teamName": "Penguins", "abv": "pit"},
             {'city': "San Jose", "teamName": "Sharks", "abv": "sj"},
             {'city': "St. Louis", "teamName": "Blues", "abv": "stl"},
             {'city': "Tampa Bay", "teamName": "Lightning", "abv": "tb"},
             {'city': "Toronto", "teamName": "Maple Leafs", "abv": "tor"},
             {'city': "Vancouver", "teamName": "Canucks", "abv": "van"},
             {'city': "Vegas", 	"teamName": 	"Golden Knights", 	"abv": 	"vgk"},
             {'city': 	"Washington", "teamName": "Capitals", "abv": "wsh"},
             {'city': 	"Winnipeg", "teamName": "Jets", "abv": 	"wpg"}]