mlb_teams = [{'city':'Arizona','teamName':'Diamondbacks','abv':'ari'},
             {'city':'Atlanta','teamName':'Braves','abv':'atl'},
             {'city':'Baltimore','teamName':'Orioles','abv':'bal'},
             {'city':'Boston','teamName':'Red Sox','abv':'bos'},
             {'city':'Chicago','teamName':'Cubs','abv':'chc'},
             {'city':'Chicago','teamName':'White Sox','abv':'chw'},
             {'city':'Cincinnati','teamName':'Reds','abv':'cin'},
             {'city':'Cleveland','teamName':'Indians','abv':'cle'},
             {'city':'Colorado','teamName':'Rockies','abv':'col'},
             {'city':'Detroit','teamName':'Tigers','abv':'det'},
             {'city':'Houston','teamName':'Astros','abv':'hou'},
             {'city':'Kansas City','teamName':'Royals','abv':'kc'},
             {'city':'Los Angeles','teamName':'Angels','abv':'laa'},
             {'city':'Los Angeles','teamName':'Dodgers','abv':'lad'},
             {'city':'Miami','teamName':'Marlins','abv':'mia'},
             {'city':'Milwaukee','teamName':'Brewers','abv':'mil'},
             {'city':'Minnesota','teamName':'Twins','abv':'min'},
             {'city':'New York', 'teamName': 'Mets', 'abv': 'nym'},
             {'city': 'New York', 'teamName': 'Yankees', 'abv': 'nyy'},
             {'city': 'Oakland', 'teamName': 'Athletics', 'abv': 'oak'},
             {'city': 'Philadelphia', 'teamName': 'Phillies', 'abv': 'phi'},
             {'city': 'Pittsburgh', 'teamName': 'Pirates', 'abv': 'pit'},
             {'city': 'San Diego', 'teamName': 'Padres', 'abv': 'sd'},
             {'city': 'San Francisco', 'teamName': 'Giants', 'abv': 'sf'},
             {'city': 'Seattle', 'teamName': 'Mariners', 'abv': 'sea'},
             {'city': 'St. Louis', 'teamName': 'Cardinals', 'abv': 'stl'},
             {'city': "Tampa Bay", "teamName": "Rays", "abv": "tb"},
             {'city': "Texas", "teamName": "Rangers", "abv": "tex"},
             {'city': "Toronto", "teamName": "Blue Jays", "abv": "tor"},
             {'city': "Washington", "teamName": "Nationals", "abv": "wsh"}]