nba_teams = [{'city':'Atlanta','teamName':'Hawks','abv':'atl'},
             {'city':'Boston','teamName':'Celtics','abv':'bos'},
             {'city':'Charlotte', 'teamName':'Hornets','abv':'cha'},
             {'city':'Chicago','teamName':'Bulls','abv':'chi'},
             {'city':'Cleveland','teamName':'Cavaliers','abv':'cle'},
             {'city':'Dallas','teamName':'Mavericks','abv':'dal'},
             {'city':'Denver','teamName':'Nuggets','abv':'den'},
             {'city':'Detroit','teamName':'Pistons','abv':'det'},
             {'city':'Golden State','teamName':'Warriors','abv':'gsw'},
             {'city':'Houston','teamName':'Rockets','abv':'hou'},
             {'city':'Indiana','teamName':'Pacers','abv':'ind'},
             {'city':'Los Angeles', 'teamName': 'Clippers', 'abv': 'lac'},
             {'city':'Los Angeles', 'teamName': 'Lakers', 'abv': 'lal'},
             {'city':'Memphis','teamName':'Grizzlies','abv':'mem'},
             {'city':'Miami','teamName':'Heat','abv':'mia'},
             {'city':'Milwaukee','teamName':'Bucks','abv':'mil'},
             {'city':'Minnesota','teamName':'Timberwolves','abv':'min'},
             {'city': 'New Orleans', 'teamName': 'Pelicans', 'abv': 'no'},
             {'city': 'New York', 'teamName': 'Knicks', 'abv': 'nyk'},
             {'city': 'Oklahoma City', 'teamName': 'Thunder', 'abv': 'okc'},
             {'city': 'Orlando', 'teamName': 'Magic', 'abv': 'orl'},
             {'city': 'Philadelphia', 'teamName': '76ers', 'abv': 'phi'},
             {'city': 'Phoenix', 'teamName': 'Suns', 'abv': 'phx'},
             {'city': "Portland", "teamName": "Trail Blazers", "abv": "por"},
             {'city': "Sacramento", "teamName": "Kings", "abv": "sac"},
             {'city': "San Antonio", "teamName": "Spurs", "abv": "sa"},
             {'city': "Toronto", "teamName": "Raptors", "abv": "tor"},
             {'city': "Utah", "teamName": "Jazz", "abv": "utah"},
             {'city': "Washington", "teamName": "Wizards", "abv": "wsh"}]