ncaab_teams = [
    {'city':'Abilene Christian','teamName':'Wildcats','abv':'ACU'},
    {'city':'Air Force','teamName':'Falcons','abv':'AF'},
    {'city':'Akron','teamName':'Zips','abv':'AKR'},
    {'city':'Alabama','teamName':'Crimson Tide','abv':'ALA'},
    {'city':'Alabama A&M','teamName':'Bulldogs','abv':'AAMU'},
    {'city':'Alabama State','teamName':'Hornets','abv':'ALST'},
    {'city':'Albany','teamName':'Great Danes','abv':'ALB'},
    {'city':'Alcorn State','teamName':'Braves','abv':'ALCN'},
    {'city':'American','teamName':'Eagles','abv':'AMER'},
    {'city':'Appalachian State','teamName':'Mountaineers','abv':'APP'},
    {'city':'Arizona','teamName':'Wildcats','abv':'ARI'},
    {'city':'Arizona State','teamName':'Sun Devils','abv':'ASU'},
    {'city':'Arkansas','teamName':'Razorbacks','abv':'ARK'},
    {'city':'Arkansas State','teamName':'Red Wolves','abv':'AST'},
    {'city':'Army','teamName':'Black Knights','abv':'ARMY'},
    {'city':'Auburn','teamName':'Tigers','abv':'AUB'},
    {'city':'Austin Peay','teamName':'Governors','abv':'PEAY'},
    {'city':'Ball State','teamName':'Cardinals','abv':'BALL'},
    {'city':'Baylor','teamName':'Bears','abv':'BAY'},
    {'city':'Bellarmine','teamName':'Knights','abv':'BELL'},
    {'city':'Belmont','teamName':'Bruins','abv':'BEL'},
    {'city':'Bethune-Cookman','teamName':'Wildcats','abv':'BCU'},
    {'city':'Binghamton','teamName':'Bearcats','abv':'BING'},
    {'city':'Boise State','teamName':'Broncos','abv':'BSU'},
    {'city':'Boston College','teamName':'Eagles','abv':'BC'},
    {'city':'Boston University','teamName':'Terriers','abv':'BU'},
    {'city':'Bowling Green','teamName':'Falcons','abv':'BGSU'},
    {'city':'Bradley','teamName':'Braves','abv':'BRAD'},
    {'city':'Brown','teamName':'Bears','abv':'BRWN'},
    {'city':'Bryant','teamName':'Bulldogs','abv':'BRY'},
    {'city':'Bucknell','teamName':'Bison','abv':'BUCK'},
    {'city':'Buffalo','teamName':'Bulls','abv':'UB'},
    {'city':'Butler','teamName':'Bulldogs','abv':'BUT'},
    {'city':'BYU','teamName':'Cougars','abv':'BYU'},
    {'city':'Cal Baptist','teamName':'Lancers','abv':'CBU'},
    {'city':'Cal Poly','teamName':'Mustangs','abv':'CP'},
    {'city':'Cal State Bakersfield','teamName':'Roadrunners','abv':'CSUB'},
    {'city':'Cal State Fullerton','teamName':'Titans','abv':'CSF'},
    {'city':'Cal State Northridge','teamName':'Matadors','abv':'CSUN'},
    {'city':'California','teamName':'Golden Bears','abv':'CAL'},
    {'city':'Campbell','teamName':'Fighting Camels','abv':'CAMP'},
    {'city':'Canisius','teamName':'Golden Griffins','abv':'CAN'},
    {'city':'Central Arkansas','teamName':'Bears','abv':'UCA'},
    {'city':'Central Connecticut','teamName':'Blue Devils','abv':'CCSU'},
    {'city':'Central Michigan','teamName':'Chippewas','abv':'CMU'},
    {'city':'Charleston Southern','teamName':'Buccaneers','abv':'CHSO'},
    {'city':'Charlotte','teamName':'49ers','abv':'CLT'},
    {'city':'Chattanooga','teamName':'Moccasins','abv':'UTC'},
    {'city':'Chicago State','teamName':'Cougars','abv':'CSU'},
    {'city':'Cincinnati','teamName':'Bearcats','abv':'CIN'},
    {'city':'Clemson','teamName':'Tigers','abv':'CLEM'},
    {'city':'Cleveland State','teamName':'Vikings','abv':'CSU'},
    {'city':'Coastal Carolina','teamName':'Chanticleers','abv':'CCU'},
    {'city':'Colgate','teamName':'Raiders','abv':'COLG'},
    {'city':'College of Charleston','teamName':'Cougars','abv':'COFC'},
    {'city':'Colorado','teamName':'Buffaloes','abv':'COLO'},
    {'city':'Colorado State','teamName':'Rams','abv':'CSU'},
    {'city':'Columbia','teamName':'Lions','abv':'COL'},
    {'city':'UConn','teamName':'Huskies','abv':'UCONN'},
    {'city':'Coppin State','teamName':'Eagles','abv':'COPP'},
    {'city':'Cornell','teamName':'Big Red','abv':'COR'},
    {'city':'Creighton','teamName':'Bluejays','abv':'CREI'},
    {'city':'Dartmouth','teamName':'Big Green','abv':'DAR'},
    {'city':'Davidson','teamName':'Wildcats','abv':'DAV'},
    {'city':'Dayton','teamName':'Flyers','abv':'DAY'},
    {'city':'Delaware','teamName':'Fightin\' Blue Hens','abv':'DEL'},
    {'city':'Delaware State','teamName':'Hornets','abv':'DSU'},
    {'city':'Denver','teamName':'Pioneers','abv':'DEN'},
    {'city':'DePaul','teamName':'Blue Demons','abv':'DEP'},
    {'city':'Detroit Mercy','teamName':'Titans','abv':'DET'},
    {'city':'Drake','teamName':'Bulldogs','abv':'DRAKE'},
    {'city':'Drexel','teamName':'Dragons','abv':'DREX'},
    {'city':'Duke','teamName':'Blue Devils','abv':'DUKE'},
    {'city':'Duquesne','teamName':'Dukes','abv':'DUQ'},
    {'city':'East Carolina','teamName':'Pirates','abv':'ECU'},
    {'city':'East Tennessee State','teamName':'Buccaneers','abv':'ETSU'},
    {'city':'Eastern Illinois','teamName':'Panthers','abv':'EIU'},
    {'city':'Eastern Kentucky','teamName':'Colonels','abv':'EKU'},
    {'city':'Eastern Michigan','teamName':'Eagles','abv':'EMU'},
    {'city':'Eastern Washington','teamName':'Eagles','abv':'EWU'},
    {'city':'Elon','teamName':'Phoenix','abv':'ELON'},
    {'city':'Evansville','teamName':'Purple Aces','abv':'EVAN'},
    {'city':'Fairfield','teamName':'Stags','abv':'FAIR'},
    {'city':'Fairleigh Dickinson','teamName':'Knights','abv':'FDU'},
    {'city':'Florida','teamName':'Gators','abv':'UF'},
    {'city':'Florida A&M','teamName':'Rattlers','abv':'FAMU'},
    {'city':'Florida Atlantic','teamName':'Owls','abv':'FAU'},
    {'city':'Florida Gulf Coast','teamName':'Eagles','abv':'FGCU'},
    {'city':'Florida International','teamName':'Panthers','abv':'FIU'},
    {'city':'Florida State','teamName':'Seminoles','abv':'FSU'},
    {'city':'Fordham','teamName':'Rams','abv':'FOR'},
    {'city':'Fresno State','teamName':'Bulldogs','abv':'FRES'},
    {'city':'Furman','teamName':'Paladins','abv':'FUR'},
    {'city':'Gardner-Webb','teamName':'Runnin\' Bulldogs','abv':'GWU'},
    {'city':'George Mason','teamName':'Patriots','abv':'GMU'},
    {'city':'George Washington','teamName':'Colonials','abv':'GW'},
    {'city':'Georgetown','teamName':'Hoyas','abv':'GTWN'},
    {'city':'Georgia','teamName':'Bulldogs','abv':'UGA'},
    {'city':'Georgia Southern','teamName':'Eagles','abv':'GASO'},
    {'city':'Georgia State','teamName':'Panthers','abv':'GAST'},
    {'city':'Georgia Tech','teamName':'Yellow Jackets','abv':'GT'},
    {'city':'Gonzaga','teamName':'Bulldogs','abv':'GONZ'},
    {'city':'Grambling State','teamName':'Tigers','abv':'GRAM'},
    {'city':'Grand Canyon','teamName':'Antelopes','abv':'GCU'},
    {'city':'Green Bay','teamName':'Phoenix','abv':'GB'},
    {'city':'Hampton','teamName':'Pirates','abv':'HAMP'},
    {'city':'Harvard','teamName':'Crimson','abv':'HARV'},
    {'city':'Hawaii','teamName':'Rainbow Warriors','abv':'HAW'},
    {'city':'High Point','teamName':'Panthers','abv':'HPU'},
    {'city':'Hofstra','teamName':'Pride','abv':'HOF'},
    {'city':'Holy Cross','teamName':'Crusaders','abv':'HC'},
    {'city':'Houston','teamName':'Cougars','abv':'HOU'},
    {'city':'Houston Christian','teamName':'Huskies','abv':'HCU'},
    {'city':'Howard','teamName':'Bison','abv':'HOW'},
    {'city':'Idaho','teamName':'Vandals','abv':'IDA'},
    {'city':'Idaho State','teamName':'Bengals','abv':'ISU'},
    {'city':'Illinois','teamName':'Fighting Illini','abv':'ILL'},
    {'city':'Illinois State','teamName':'Redbirds','abv':'ILST'},
    {'city':'Incarnate Word','teamName':'Cardinals','abv':'UIW'},
    {'city':'Indiana','teamName':'Hoosiers','abv':'IU'},
    {'city':'Indiana State','teamName':'Sycamores','abv':'INST'},
    {'city':'Iona','teamName':'Gaels','abv':'IONA'},
    {'city':'Iowa','teamName':'Hawkeyes','abv':'IOWA'},
    {'city':'Iowa State','teamName':'Cyclones','abv':'ISU'},
    {'city':'Jackson State','teamName':'Tigers','abv':'JKST'},
    {'city':'Jacksonville','teamName':'Dolphins','abv':'JU'},
    {'city':'Jacksonville State','teamName':'Gamecocks','abv':'JSU'},
    {'city':'James Madison','teamName':'Dukes','abv':'JMU'},
    {'city':'Kansas','teamName':'Jayhawks','abv':'KU'},
    {'city':'Kansas State','teamName':'Wildcats','abv':'KSU'},
    {'city':'Kennesaw State','teamName':'Owls','abv':'KSU'},
    {'city':'Kent State','teamName':'Golden Flashes','abv':'KENT'},
    {'city':'Lafayette','teamName':'Leopards','abv':'LAF'},
    {'city':'La Salle','teamName':'Explorers','abv':'LAS'},
    {'city':'Lehigh','teamName':'Mountain Hawks','abv':'LEH'},
    {'city':'Liberty','teamName':'Flames','abv':'LIB'},
    {'city':'Lindenwood','teamName':'Lions','abv':'LIN'},
    {'city':'Long Beach State','teamName':'Beach','abv':'LBSU'},
    {'city':'Long Island','teamName':'Sharks','abv':'LIU'},
    {'city':'Longwood','teamName':'Lancers','abv':'LONG'},
    {'city':'Louisiana','teamName':'Ragin\' Cajuns','abv':'ULL'},
    {'city':'Louisiana Tech','teamName':'Bulldogs','abv':'LT'},
    {'city':'Louisville','teamName':'Cardinals','abv':'LOU'},
    {'city':'Loyola Chicago','teamName':'Ramblers','abv':'LUC'},
    {'city':'Loyola Maryland','teamName':'Greyhounds','abv':'LOY'},
    {'city':'Loyola Marymount','teamName':'Lions','abv':'LMU'},
    {'city':'LSU','teamName':'Tigers','abv':'LSU'},
    {'city':'Maine','teamName':'Black Bears','abv':'ME'},
    {'city':'Manhattan','teamName':'Jaspers','abv':'MAN'},
    {'city':'Marist','teamName':'Red Foxes','abv':'MAR'},
    {'city':'Marquette','teamName':'Golden Eagles','abv':'MARQ'},
    {'city':'Marshall','teamName':'Thundering Herd','abv':'MRSH'},
    {'city':'Maryland','teamName':'Terrapins','abv':'MD'},
    {'city':'UMass','teamName':'Minutemen','abv':'UMASS'},
    {'city':'UMass Lowell','teamName':'River Hawks','abv':'UML'},
    {'city':'McNeese State','teamName':'Cowboys','abv':'MCN'},
    {'city':'Memphis','teamName':'Tigers','abv':'MEM'},
    {'city':'Mercer','teamName':'Bears','abv':'MER'},
    {'city':'Merrimack','teamName':'Warriors','abv':'MERR'},
    {'city':'Miami (FL)','teamName':'Hurricanes','abv':'MIA'},
    {'city':'Miami (OH)','teamName':'RedHawks','abv':'MIOH'},
    {'city':'Michigan','teamName':'Wolverines','abv':'MICH'},
    {'city':'Michigan State','teamName':'Spartans','abv':'MSU'},
    {'city':'Middle Tennessee','teamName':'Blue Raiders','abv':'MTSU'},
    {'city':'Milwaukee','teamName':'Panthers','abv':'MIL'},
    {'city':'Minnesota','teamName':'Golden Gophers','abv':'MINN'},
    {'city':'Mississippi State','teamName':'Bulldogs','abv':'MSST'},
    {'city':'Missouri','teamName':'Tigers','abv':'MIZ'},
    {'city':'Missouri State','teamName':'Bears','abv':'MOST'},
    {'city':'Monmouth','teamName':'Hawks','abv':'MON'},
    {'city':'Montana','teamName':'Grizzlies','abv':'MONT'},
    {'city':'Montana State','teamName':'Bobcats','abv':'MTST'},
    {'city':'Morehead State','teamName':'Eagles','abv':'MORE'},
    {'city':'Morgan State','teamName':'Bears','abv':'MORG'},
    {'city':'Mount St. Mary\'s','teamName':'Mountaineers','abv':'MSM'},
    {'city':'Murray State','teamName':'Racers','abv':'MUR'},
    {'city':'Navy','teamName':'Midshipmen','abv':'NAVY'},
    {'city':'NC State','teamName':'Wolfpack','abv':'NCST'},
    {'city':'Nebraska','teamName':'Cornhuskers','abv':'NEB'},
    {'city':'Nevada','teamName':'Wolf Pack','abv':'NEV'},
    {'city':'New Hampshire','teamName':'Wildcats','abv':'UNH'},
    {'city':'New Mexico','teamName':'Lobos','abv':'UNM'},
    {'city':'New Mexico State','teamName':'Aggies','abv':'NMSU'},
    {'city':'New Orleans','teamName':'Privateers','abv':'UNO'},
    {'city':'Niagara','teamName':'Purple Eagles','abv':'NIA'},
    {'city':'Nicholls State','teamName':'Colonels','abv':'NICH'},
    {'city':'NJIT','teamName':'Highlanders','abv':'NJIT'},
    {'city':'Norfolk State','teamName':'Spartans','abv':'NSU'},
    {'city':'North Carolina','teamName':'Tar Heels','abv':'UNC'},
    {'city':'North Carolina A&T','teamName':'Aggies','abv':'NCAT'},
    {'city':'North Carolina Central','teamName':'Eagles','abv':'NCCU'},
    {'city':'North Dakota','teamName':'Fighting Hawks','abv':'UND'},
    {'city':'North Dakota State','teamName':'Bison','abv':'NDSU'},
    {'city':'North Florida','teamName':'Ospreys','abv':'UNF'},
    {'city':'North Texas','teamName':'Mean Green','abv':'UNT'},
    {'city':'Northeastern','teamName':'Huskies','abv':'NU'},
    {'city':'Northern Arizona','teamName':'Lumberjacks','abv':'NAU'},
    {'city':'Northern Colorado','teamName':'Bears','abv':'UNCO'},
    {'city':'Northern Illinois','teamName':'Huskies','abv':'NIU'},
    {'city':'Northern Kentucky','teamName':'Norse','abv':'NKU'},
    {'city':'Northwestern','teamName':'Wildcats','abv':'NU'},
    {'city':'Northwestern State','teamName':'Demons','abv':'NWST'},
    {'city':'Notre Dame','teamName':'Fighting Irish','abv':'ND'},
    {'city':'Oakland','teamName':'Golden Grizzlies','abv':'OAK'},
    {'city':'Ohio','teamName':'Bobcats','abv':'OHIO'},
    {'city':'Ohio State','teamName':'Buckeyes','abv':'OSU'},
    {'city':'Oklahoma','teamName':'Sooners','abv':'OU'},
    {'city':'Oklahoma State','teamName':'Cowboys','abv':'OKST'},
    {'city':'Old Dominion','teamName':'Monarchs','abv':'ODU'},
    {'city':'Ole Miss','teamName':'Rebels','abv':'MISS'},
    {'city':'Oral Roberts','teamName':'Golden Eagles','abv':'ORU'},
    {'city':'Oregon','teamName':'Ducks','abv':'ORE'},
    {'city':'Oregon State','teamName':'Beavers','abv':'OSU'},
    {'city':'Pacific','teamName':'Tigers','abv':'PAC'},
    {'city':'Penn State','teamName':'Nittany Lions','abv':'PSU'},
    {'city':'Pennsylvania','teamName':'Quakers','abv':'PENN'},
    {'city':'Pepperdine','teamName':'Waves','abv':'PEPP'},
    {'city':'Pittsburgh','teamName':'Panthers','abv':'PITT'},
    {'city':'Portland','teamName':'Pilots','abv':'POR'},
    {'city':'Portland State','teamName':'Vikings','abv':'PSU'},
    {'city':'Prairie View A&M','teamName':'Panthers','abv':'PVAMU'},
    {'city':'Presbyterian','teamName':'Blue Hose','abv':'PC'},
    {'city':'Princeton','teamName':'Tigers','abv':'PRIN'},
    {'city':'Providence','teamName':'Friars','abv':'PROV'},
    {'city':'Purdue','teamName':'Boilermakers','abv':'PUR'},
    {'city':'Purdue Fort Wayne','teamName':'Mastodons','abv':'PFW'},
    {'city':'Quinnipiac','teamName':'Bobcats','abv':'QUIN'},
    {'city':'Radford','teamName':'Highlanders','abv':'RAD'},
    {'city':'Rhode Island','teamName':'Rams','abv':'URI'},
    {'city':'Rice','teamName':'Owls','abv':'RICE'},
    {'city':'Richmond','teamName':'Spiders','abv':'RICH'},
    {'city':'Rider','teamName':'Broncs','abv':'RID'},
    {'city':'Robert Morris','teamName':'Colonials','abv':'RMU'},
    {'city':'Rutgers','teamName':'Scarlet Knights','abv':'RUT'},
    {'city':'Sacramento State','teamName':'Hornets','abv':'SAC'},
    {'city':'Sacred Heart','teamName':'Pioneers','abv':'SHU'},
    {'city':'Sam Houston','teamName':'Bearkats','abv':'SHSU'},
    {'city':'Samford','teamName':'Bulldogs','abv':'SAM'},
    {'city':'San Diego','teamName':'Toreros','abv':'USD'},
    {'city':'San Diego State','teamName':'Aztecs','abv':'SDSU'},
    {'city':'San Francisco','teamName':'Dons','abv':'USF'},
    {'city':'San Jose State','teamName':'Spartans','abv':'SJSU'},
    {'city':'Santa Clara','teamName':'Broncos','abv':'SCU'},
    {'city':'Seattle','teamName':'Redhawks','abv':'SEA'},
    {'city':'Seton Hall','teamName':'Pirates','abv':'SHU'},
    {'city':'Siena','teamName':'Saints','abv':'SIE'},
    {'city':'South Alabama','teamName':'Jaguars','abv':'USA'},
    {'city':'South Carolina','teamName':'Gamecocks','abv':'SC'},
    {'city':'South Carolina State','teamName':'Bulldogs','abv':'SCSU'},
    {'city':'South Dakota','teamName':'Coyotes','abv':'USD'},
    {'city':'South Dakota State','teamName':'Jackrabbits','abv':'SDSU'},
    {'city':'Southeast Missouri State','teamName':'Redhawks','abv':'SEMO'},
    {'city':'Southeastern Louisiana','teamName':'Lions','abv':'SELA'},
    {'city':'Southern','teamName':'Jaguars','abv':'SOU'},
    {'city':'Southern Illinois','teamName':'Salukis','abv':'SIU'},
    {'city':'Southern Illinois Edwardsville','teamName':'Cougars','abv':'SIUE'},
    {'city':'Southern Miss','teamName':'Golden Eagles','abv':'USM'},
    {'city':'Southern Utah','teamName':'Thunderbirds','abv':'SUU'},
    {'city':'St. Bonaventure','teamName':'Bonnies','abv':'SBU'},
    {'city':'St. Francis (PA)','teamName':'Red Flash','abv':'SFPA'},
    {'city':'St. John\'s','teamName':'Red Storm','abv':'SJU'},
    {'city':'St. Joseph\'s','teamName':'Hawks','abv':'SJU'},
    {'city':'St. Louis','teamName':'Billikens','abv':'SLU'},
    {'city':'St. Mary\'s','teamName':'Gaels','abv':'SMC'},
    {'city':'St. Peter\'s','teamName':'Peacocks','abv':'SPU'},
    {'city':'Stanford','teamName':'Cardinal','abv':'STAN'},
    {'city':'Stephen F. Austin','teamName':'Lumberjacks','abv':'SFA'},
    {'city':'Stetson','teamName':'Hatters','abv':'STET'},
    {'city':'Stonehill','teamName':'Skyhawks','abv':'STON'},
    {'city':'Stony Brook','teamName':'Seawolves','abv':'SBU'},
    {'city':'Syracuse','teamName':'Orange','abv':'CUSE'},
    {'city':'Tarleton State','teamName':'Texans','abv':'TSU'},
    {'city':'Temple','teamName':'Owls','abv':'TEM'},
    {'city':'Tennessee','teamName':'Volunteers','abv':'TENN'},
    {'city':'Tennessee State','teamName':'Tigers','abv':'TSU'},
    {'city':'Tennessee Tech','teamName':'Golden Eagles','abv':'TTU'},
    {'city':'Texas','teamName':'Longhorns','abv':'UT'},
    {'city':'Texas A&M','teamName':'Aggies','abv':'TAMU'},
    {'city':'Texas A&M-Corpus Christi','teamName':'Islanders','abv':'AMCC'},
    {'city':'Texas Christian','teamName':'Horned Frogs','abv':'TCU'},
    {'city':'Texas Southern','teamName':'Tigers','abv':'TXSO'},
    {'city':'Texas State','teamName':'Bobcats','abv':'TXST'},
    {'city':'Texas Tech','teamName':'Red Raiders','abv':'TTU'},
    {'city':'The Citadel','teamName':'Bulldogs','abv':'CIT'},
    {'city':'Toledo','teamName':'Rockets','abv':'TOL'},
    {'city':'Towson','teamName':'Tigers','abv':'TOW'},
    {'city':'Troy','teamName':'Trojans','abv':'TROY'},
    {'city':'Tulane','teamName':'Green Wave','abv':'TULN'},
    {'city':'Tulsa','teamName':'Golden Hurricane','abv':'TULS'},
    {'city':'UAB','teamName':'Blazers','abv':'UAB'},
    {'city':'UC Davis','teamName':'Aggies','abv':'UCD'},
    {'city':'UC Irvine','teamName':'Anteaters','abv':'UCI'},
    {'city':'UC Riverside','teamName':'Highlanders','abv':'UCR'},
    {'city':'UC San Diego','teamName':'Tritons','abv':'UCSD'},
    {'city':'UC Santa Barbara','teamName':'Gauchos','abv':'UCSB'},
    {'city':'UCF','teamName':'Knights','abv':'UCF'},
    {'city':'UCLA','teamName':'Bruins','abv':'UCLA'},
    {'city':'UMBC','teamName':'Retrievers','abv':'UMBC'},
    {'city':'UNC Asheville','teamName':'Bulldogs','abv':'UNCA'},
    {'city':'UNC Greensboro','teamName':'Spartans','abv':'UNCG'},
    {'city':'UNC Wilmington','teamName':'Seahawks','abv':'UNCW'},
    {'city':'UNLV','teamName':'Rebels','abv':'UNLV'},
    {'city':'USC','teamName':'Trojans','abv':'USC'},
    {'city':'UT Arlington','teamName':'Mavericks','abv':'UTA'},
    {'city':'UT Martin','teamName':'Skyhawks','abv':'UTM'},
    {'city':'UTEP','teamName':'Miners','abv':'UTEP'},
    {'city':'UTSA','teamName':'Roadrunners','abv':'UTSA'},
    {'city':'Valparaiso','teamName':'Beacons','abv':'VAL'},
    {'city':'Vanderbilt','teamName':'Commodores','abv':'VANDY'},
    {'city':'VCU','teamName':'Rams','abv':'VCU'},
    {'city':'Vermont','teamName':'Catamounts','abv':'UVM'},
    {'city':'Villanova','teamName':'Wildcats','abv':'NOVA'},
    {'city':'Virginia','teamName':'Cavaliers','abv':'UVA'},
    {'city':'Virginia Tech','teamName':'Hokies','abv':'VT'},
    {'city':'VMI','teamName':'Keydets','abv':'VMI'},
    {'city':'Wagner','teamName':'Seahawks','abv':'WAG'},
    {'city':'Wake Forest','teamName':'Demon Deacons','abv':'WAKE'},
    {'city':'Washington','teamName':'Huskies','abv':'UW'},
    {'city':'Washington State','teamName':'Cougars','abv':'WSU'},
    {'city':'Weber State','teamName':'Wildcats','abv':'WEB'},
    {'city':'West Virginia','teamName':'Mountaineers','abv':'WVU'},
    {'city':'Western Carolina','teamName':'Catamounts','abv':'WCU'},
    {'city':'Western Illinois','teamName':'Leathernecks','abv':'WIU'},
    {'city':'Western Kentucky','teamName':'Hilltoppers','abv':'WKU'},
    {'city':'Western Michigan','teamName':'Broncos','abv':'WMU'},
    {'city':'Wichita State','teamName':'Shockers','abv':'WICH'},
    {'city':'William & Mary','teamName':'Tribe','abv':'W&M'},
    {'city':'Winthrop','teamName':'Eagles','abv':'WIN'},
    {'city':'Wofford','teamName':'Terriers','abv':'WOF'},
    {'city':'Wright State','teamName':'Raiders','abv':'WRST'},
    {'city':'Wyoming','teamName':'Cowboys','abv':'WYO'},
    {'city':'Xavier','teamName':'Musketeers','abv':'XAV'},
    {'city':'Yale','teamName':'Bulldogs','abv':'YALE'},
    {'city':'Youngstown State','teamName':'Penguins','abv':'YSU'}
]